### ISSUE TITLE
ok pay @username amount

### ISSUE THREAD

**Issue by xplrkai** [mxttx/okbot-issue-tracker#10]
## Summary
Similar to retros, ykno, it should just be like ok pay @username amount to give them a certain amount. I think this would be a good addition.

## Reasoning
There's probably many more good reasons that I can't think of, but for example, if someone gets stolen from and it's practically all their money, maybe you'd wanna donate to them 

## Quality Assurance
I guess in some situations it couldddd maybe be considered overpowered, but it should also take it out of the givers balance, making it less OP.

**Comment by mxttx** [comment]
Thank you for the suggestion but this will be closed as it is a [duplicate](https://github.com/mxttx/okbot-issue-tracker/issues/6).

This suggestion will be implemented soon to the development bot.
You can get early access to the updates by becoming a Beta Tester - see our official Discord guild for more details!
