### ISSUE TITLE
Increase bank limit with daily gift.

### ISSUE THREAD

**Issue by cammybruh** [mxttx/okbot-issue-tracker#12]
## Summary
Increase bank limit with daily gift.

## Reasoning
Right now the only way you can increase your bank balance is by doing tasks, this is extremely slow. In the daily gift it should give you 500 more on your bank limit. I know more ways of increasing this is coming however for now this would be a hot fix.

## Quality Assurance
Quality game play bruva.

**Comment by mxttx** [comment]
This will be added in the next version. Thank you for the suggestion!
